# Generated by Django 6.0.7 on 2026-08-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('path', models.CharField(db_index=True, max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('h1', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('page_type', models.CharField(blank=True, max_length=32)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('in_sitemap', models.BooleanField(default=True)),
                ('total_clicks_28d', models.IntegerField(default=0)),
                ('total_impressions_28d', models.IntegerField(default=0)),
                ('ranking_keyword_count', models.IntegerField(default=0)),
                ('sessions_28d', models.IntegerField(default=0)),
                ('conversions_28d', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(blank=True, null=True)),
                ('revenue_28d', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('embedding_blob', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_pages', to='clients.market')),
            ],
            options={
                'unique_together': {('market', 'url')},
            },
        ),
    ]
