# Generated by Django 5.2.17 on 2026-08-11 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('pages', '0001_initial'),
        ('runs', '0005_alter_runstage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_on', models.DateField()),
                ('keyword', models.CharField(max_length=500)),
                ('keyword_normalised', models.CharField(db_index=True, max_length=500)),
                ('page_url', models.URLField(max_length=1000)),
                ('country', models.CharField(max_length=3)),
                ('clicks', models.FloatField(default=0)),
                ('impressions', models.FloatField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('position', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_snapshots', to='runs.run')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_snapshots', to='clients.market')),
            ],
            options={
                'indexes': [models.Index(fields=['market', 'keyword_normalised', 'observed_on'], name='pages_posit_market__a05c18_idx'), models.Index(fields=['market', 'page_url', 'observed_on'], name='pages_posit_market__5946ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('market', 'observed_on', 'keyword_normalised', 'page_url', 'country'), name='unique_daily_gsc_position')],
            },
        ),
    ]
