# Generated by Django 6.0.7 on 2026-08-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('full', 'Full Run'), ('gsc_delta', 'GSC Delta (Weekly)'), ('rescore', 'Rescore Only')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('markets', models.JSONField(default=list, help_text='List of market codes to include, e.g. ["UK", "DE"]')),
                ('seed_keywords', models.TextField(blank=True, help_text='Comma-separated seed keywords for DataForSEO keyword research.')),
                ('competitor_domains', models.TextField(blank=True, help_text='Comma-separated competitor domains for gap analysis. Leave blank to use the competitors already configured in the Market.')),
                ('settings_snapshot', models.JSONField(default=dict, help_text='Frozen copy of EngineSettings + ScoringWeights at run start.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, help_text='Accumulated DataForSEO spend for this run.', max_digits=10)),
                ('sheet_url', models.URLField(blank=True, help_text='Link to the output Google Sheet.')),
                ('error', models.TextField(blank=True, help_text='Error details if the run failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('plan', 'Stage 0 — Plan'), ('ingest', 'Stage 1 — Ingest'), ('normalise', 'Stage 2 — Normalise'), ('enrich', 'Stage 3 — Enrich'), ('cluster', 'Stage 4 — Cluster'), ('match', 'Stage 5 — Match'), ('decide', 'Stage 6 — Decide'), ('cross_market', 'Stage 7 — Cross-Market'), ('score', 'Stage 8 — Score'), ('export', 'Stage 9 — Export')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('records_in', models.IntegerField(default=0)),
                ('records_out', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='runs.run')),
            ],
            options={
                'ordering': ['run', 'pk'],
                'unique_together': {('run', 'name')},
            },
        ),
    ]
