# Generated by Django 5.2.17 on 2026-08-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="settings_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Frozen copy of EngineSettings + ScoringWeights at run start.",
                null=True,
            ),
        ),
    ]
