# Generated by Django 5.2.17 on 2026-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_alter_run_settings_snapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runstage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("complete", "Complete"),
                    ("partial", "Partial"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
