# Generated by Django 5.2.17 on 2026-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_alter_runstage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstage',
            name='name',
            field=models.CharField(choices=[('plan', 'Stage 0 — Plan'), ('ingest', 'Stage 1 — Ingest'), ('sitemap', 'Stage 1b - Sitemap'), ('normalise', 'Stage 2 — Normalise'), ('analytics', 'Stage 2b - GSC/GA4 Analytics'), ('enrich', 'Stage 3 — Enrich'), ('cluster', 'Stage 4 — Cluster'), ('match', 'Stage 5 — Match'), ('decide', 'Stage 6 — Decide'), ('cross_market', 'Stage 7 — Cross-Market'), ('score', 'Stage 8 — Score'), ('export', 'Stage 9 — Export')], max_length=40),
        ),
    ]
