# Generated by Django 5.2.17 on 2026-08-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_alter_runstage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='markets',
            field=models.JSONField(default=list, help_text='JSON array of market codes, e.g. ["UK"] or ["UK","US"]. Codes must match Market.code values for this client.'),
        ),
        migrations.AlterField(
            model_name='run',
            name='seed_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated list of seed keywords, e.g. running shoes, trail shoes, minimalist running'),
        ),
    ]
