# Generated by Django 6.0.7 on 2026-08-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(max_length=300)),
                ('primary_keyword', models.CharField(max_length=500)),
                ('primary_keyword_volume', models.IntegerField(default=0)),
                ('total_search_volume', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('intent', models.CharField(blank=True, max_length=20)),
                ('cross_market_group', models.CharField(blank=True, db_index=True, max_length=64)),
                ('centroid_blob', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='clients.client')),
                ('first_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics_found', to='runs.run')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='clients.market')),
            ],
        ),
        migrations.CreateModel(
            name='TopicKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=500)),
                ('search_volume', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('our_position', models.FloatField(blank=True, null=True)),
                ('keyword_difficulty', models.IntegerField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='topics.topic')),
            ],
            options={
                'ordering': ['-is_primary', '-search_volume'],
            },
        ),
    ]
