# Generated by Django 6.0.7 on 2026-08-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('runs', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('new_content', 'New Content'), ('optimise', 'Optimise'), ('merge', 'Merge (Cannibalisation)'), ('ignore', 'Ignore')], max_length=20)),
                ('target_urls', models.JSONField(default=list)),
                ('why_flagged', models.JSONField(default=list)),
                ('current_position', models.FloatField(blank=True, null=True)),
                ('previous_position', models.FloatField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('difficulty_score', models.IntegerField(blank=True, null=True)),
                ('page_type', models.CharField(blank=True, max_length=32)),
                ('suggested_slug', models.CharField(blank=True, max_length=300)),
                ('conversion_potential', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('conversion_basis', models.CharField(blank=True, choices=[('data', 'GA4 Data'), ('inferred', 'Inferred'), ('unknown', 'Unknown')], max_length=20)),
                ('competitor_url', models.URLField(blank=True, max_length=1000)),
                ('ai_search_opportunity', models.BooleanField(blank=True, null=True)),
                ('estimated_impact', models.JSONField(blank=True, help_text='Expected traffic/revenue gain if target position is reached.', null=True)),
                ('priority_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, help_text="Engine's confidence in this recommendation (0.0 to 1.0).", null=True)),
                ('decision_trace', models.JSONField(default=dict, help_text='A complete log of WHY the engine chose this action. Used for debugging.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='clients.market')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='runs.run')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='topics.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['run', '-priority_score'], name='opportuniti_run_id_0dafd9_idx')],
                'unique_together': {('run', 'topic')},
            },
        ),
    ]
