"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# settings/__init__.py → settings/ → config/ → engine/ (project root)
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Read .env file from the engine/ directory (where manage.py lives)
env = environ.Env(
    DJANGO_DEBUG=(bool, True),
)
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', default='django-insecure-hudikwzx5+iv&z(l7l%)7m47(m@yh(hp5s2+o6@eo_pa!44#q8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DJANGO_DEBUG')

# --- DataForSEO API Credentials ---
DATAFORSEO_LOGIN = env('DATAFORSEO_LOGIN', default='')
DATAFORSEO_PASSWORD = env('DATAFORSEO_PASSWORD', default='')

# --- Google Sheets export ---
# Fixture mode is deliberately the safe default. Set USE_DUMMY_SHEETS=False
# only after configuring a service-account key and target spreadsheet.
USE_DUMMY_SHEETS = env.bool('USE_DUMMY_SHEETS', default=True)
GOOGLE_SHEETS_SERVICE_ACCOUNT_FILE = env(
    'GOOGLE_SHEETS_SERVICE_ACCOUNT_FILE', default=''
)
GOOGLE_SHEETS_SPREADSHEET_ID = env('GOOGLE_SHEETS_SPREADSHEET_ID', default='')
GOOGLE_DRIVE_PARENT_FOLDER_ID = env('GOOGLE_DRIVE_PARENT_FOLDER_ID', default='')
ADMIN_GOOGLE_EMAIL = env('ADMIN_GOOGLE_EMAIL', default='')
SHEETS_MOCK_FILE = BASE_DIR / 'tests' / 'fixtures' / 'sheets_mock.json'

# GSC/GA4 response fixtures remain the safe default. The live transport uses
# a separate credential setting so Sheets and read-only analytics access can
# be deployed or rotated independently.
GOOGLE_USE_DUMMY_DATA = env.bool('GOOGLE_USE_DUMMY_DATA', default=True)
GOOGLE_API_SERVICE_ACCOUNT_FILE = env(
    'GOOGLE_API_SERVICE_ACCOUNT_FILE', default=''
)
GOOGLE_API_TIMEOUT_SECONDS = env.int('GOOGLE_API_TIMEOUT_SECONDS', default=60)

# --- Background pipeline execution ---
CELERY_BROKER_URL = env(
    'CELERY_BROKER_URL', default='redis://localhost:6379/0'
)
CELERY_RESULT_BACKEND = env(
    'CELERY_RESULT_BACKEND', default='redis://localhost:6379/0'
)
# Windows + Python 3.14: billiard shared-memory semaphores are not supported.
# solo pool runs tasks in the worker process directly (no subprocess spawning).
# This is fine for our single-pipeline-at-a-time workload.
CELERY_WORKER_POOL = env('CELERY_WORKER_POOL', default='solo')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.clients',
    'apps.runs',
    'apps.ingestion',
    'apps.pages',
    'apps.topics',
    'apps.opportunities',
    'apps.exports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL')
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# Use BigAutoField (64-bit int) — KeywordObservation can easily hit millions of rows
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

UNFOLD = {
    "SITE_TITLE": "Engine 1 Admin",
    "SITE_HEADER": "Engine 1",
}
