# Generated by Django 6.0.7 on 2026-08-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('primary_domain', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('country_iso', models.CharField(max_length=2)),
                ('language_code', models.CharField(max_length=5)),
                ('dataforseo_location_code', models.IntegerField()),
                ('gsc_property', models.CharField(max_length=255)),
                ('ga4_property_id', models.CharField(blank=True, max_length=50)),
                ('sitemap_url', models.URLField()),
                ('url_pattern', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='clients.client')),
            ],
            options={
                'unique_together': {('client', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EngineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_extraction_regex', models.CharField(default='^/([^/]+)/', help_text='Regex to extract category from URL. Default grabs the first folder path.', max_length=255)),
                ('quick_win_min_position', models.FloatField(default=7.0)),
                ('quick_win_max_position', models.FloatField(default=20.0)),
                ('decay_baseline_max_position', models.FloatField(default=5.0)),
                ('decay_current_min_position', models.FloatField(default=5.0)),
                ('decay_min_drop', models.FloatField(default=3.0)),
                ('decay_baseline_days', models.IntegerField(default=90)),
                ('decay_comparison_days', models.IntegerField(default=28)),
                ('min_search_volume', models.IntegerField(default=50)),
                ('min_keywords_per_topic', models.IntegerField(default=1)),
                ('max_keyword_difficulty', models.IntegerField(default=100)),
                ('serp_overlap_threshold', models.IntegerField(default=3)),
                ('semantic_similarity_threshold', models.FloatField(default=0.82)),
                ('clustering_linkage', models.CharField(default='complete', max_length=20)),
                ('existing_page_match_threshold', models.FloatField(default=0.75)),
                ('cannibalisation_min_pages', models.IntegerField(default=2)),
                ('max_rows_per_run', models.IntegerField(default=500)),
                ('include_ignored_rows', models.BooleanField(default=True)),
                ('max_serp_calls_per_run', models.IntegerField(default=5000)),
                ('max_spend_per_run_usd', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.market')),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='clients.market')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_volume', models.FloatField(default=0.25)),
                ('w_position_opportunity', models.FloatField(default=0.2)),
                ('w_conversion', models.FloatField(default=0.2)),
                ('w_difficulty', models.FloatField(default=0.15)),
                ('w_signal', models.FloatField(default=0.1)),
                ('w_market', models.FloatField(default=0.1)),
                ('signal_weights', models.JSONField(default=dict)),
                ('market_weights', models.JSONField(default=dict)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
