# Generated by Django 5.2.17 on 2026-08-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enginesettings",
            options={
                "verbose_name": "engine settings",
                "verbose_name_plural": "engine settings",
            },
        ),
        migrations.AlterModelOptions(
            name="scoringweights",
            options={
                "verbose_name": "scoring weights",
                "verbose_name_plural": "scoring weights",
            },
        ),
    ]
