# Generated by Django 5.2.17 on 2026-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_enginesettings_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="google_sheets_spreadsheet_id",
            field=models.CharField(
                "Google Sheets spreadsheet ID",
                blank=True,
                help_text="Destination Google spreadsheet ID for this client's recurring exports. Use the value between /d/ and /edit in the Google Sheets URL.",
                max_length=255,
            ),
        ),
    ]
