# Generated by Django 5.2.17 on 2026-08-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_google_sheets_spreadsheet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='dataforseo_location_code',
            field=models.IntegerField(help_text='DataForSEO location code, e.g. 2826 for United Kingdom. See https://docs.dataforseo.com/v3/appendix/google/locations/'),
        ),
        migrations.AlterField(
            model_name='market',
            name='ga4_property_id',
            field=models.CharField(blank=True, help_text='Leave blank to skip GA4 data. Format: 123456789', max_length=50),
        ),
        migrations.AlterField(
            model_name='market',
            name='gsc_property',
            field=models.CharField(help_text='Exact property string from Google Search Console. Domain properties: sc-domain:example.com — URL prefix: https://example.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='scoringweights',
            name='market_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scoringweights',
            name='signal_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
