# Generated by Django 6.0.7 on 2026-08-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=500)),
                ('keyword_normalised', models.CharField(db_index=True, help_text='Lowercased, stopwords removed, lemmatised, tokens sorted.', max_length=500)),
                ('source', models.CharField(max_length=32)),
                ('signal', models.CharField(choices=[('keyword_research', 'Keyword Research'), ('competitor_gap', 'Competitor Gap'), ('competitor_top_page', 'Competitor Top Page'), ('quick_win', 'Quick Win (Position 7-20)'), ('ranking_decay', 'Ranking Decay'), ('existing_ranking', 'Existing Ranking'), ('conversion_proven', 'Conversion Proven'), ('cross_market', 'Proven in Other Market')], help_text='Why this keyword was flagged — maps to column 11 (Why Flagged).', max_length=40)),
                ('search_volume', models.IntegerField(blank=True, null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('keyword_difficulty', models.IntegerField(blank=True, null=True)),
                ('competition', models.FloatField(blank=True, null=True)),
                ('our_position', models.FloatField(blank=True, null=True)),
                ('our_url', models.URLField(blank=True, max_length=1000)),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('ctr', models.FloatField(blank=True, null=True)),
                ('competitor_domain', models.CharField(blank=True, max_length=255)),
                ('competitor_url', models.URLField(blank=True, max_length=1000)),
                ('competitor_position', models.FloatField(blank=True, null=True)),
                ('serp_features', models.JSONField(default=list, help_text='SERP features present, e.g. ["ai_overview", "featured_snippet", "paa"]')),
                ('serp_top_urls', models.JSONField(default=list, help_text='Top 10 URLs from the SERP — used for clustering (SERP overlap).')),
                ('intent', models.CharField(blank=True, help_text='informational | commercial | transactional | navigational', max_length=20)),
                ('embedding_blob', models.BinaryField(blank=True, help_text='768-dim embedding stored as bytes. Will become a pgvector VectorField.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_observations', to='clients.market')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_observations', to='runs.run')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'market', 'keyword_normalised'], name='ingestion_k_run_id_fd0f49_idx'), models.Index(fields=['market', 'signal'], name='ingestion_k_market__1624f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawFetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('dataforseo', 'DataForSEO'), ('gsc', 'Google Search Console'), ('ga4', 'Google Analytics 4'), ('sitemap', 'Sitemap Crawler')], max_length=32)),
                ('endpoint', models.CharField(help_text='API endpoint called, e.g. /v3/dataforseo_labs/google/keyword_ideas/live', max_length=128)),
                ('request_params', models.JSONField(help_text='The exact parameters sent to the API.')),
                ('request_hash', models.CharField(db_index=True, help_text='SHA-256 hash of (source + endpoint + sorted params). Used for cache lookups.', max_length=64)),
                ('payload', models.JSONField(help_text='The raw API response JSON. Immutable — never modified after creation.')),
                ('cost_usd', models.DecimalField(decimal_places=5, default=0, help_text='Cost of this specific API call in USD.', max_digits=10)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_fetches', to='clients.market')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_fetches', to='runs.run')),
            ],
            options={
                'indexes': [models.Index(fields=['market', 'source', 'fetched_at'], name='ingestion_r_market__9cd7aa_idx'), models.Index(fields=['request_hash', 'fetched_at'], name='ingestion_r_request_1ac6f0_idx')],
            },
        ),
    ]
