# Generated by Django 5.2.17 on 2026-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('ingestion', '0002_keyword_observation_identity'),
        ('runs', '0005_alter_runstage_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keywordobservation',
            name='unique_keyword_observation_identity',
        ),
        migrations.AddConstraint(
            model_name='keywordobservation',
            constraint=models.UniqueConstraint(fields=('run', 'market', 'keyword_normalised', 'source', 'signal', 'competitor_domain', 'our_url'), name='unique_keyword_observation_identity'),
        ),
    ]
