# Generated by Django 5.2.17 on 2026-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ingestion",
            "0003_remove_keywordobservation_unique_keyword_observation_identity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="keywordobservation",
            name="previous_position",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
