# Generated by Django 5.2.17 on 2026-08-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_keywordobservation_previous_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawfetch',
            options={'verbose_name': 'raw fetch', 'verbose_name_plural': 'raw fetches'},
        ),
    ]
